### ISSUE TITLE
update BAB page

### ISSUE THREAD

**Issue by MarnixCroes** [WalletWasabi/WasabiWalletWebSite#25]
reminder issue

- update the page (remove Christmas stuff) if BAB is continued
- remove the page if BAB is discontinued

or maybe even if BAB is continued we might not want to have a dedicated page for it on the website
we could move the/some stuff to the docs

**Comment by MaxHillebrand** [comment]
Add this https://github.com/zkSNACKs/WalletWasabi/issues/12446#issuecomment-1943048620

@CAnorbo please deploy before the release.

**Comment by CAnorbo** [comment]
https://github.com/zkSNACKs/WasabiWalletWebSite/pull/27
